react_article
mate-academy/react_article pull request #1149
Opened 2022-10-10 18:35 UTC by xiimiik

[DEMO LINK](https://xiimiik.github.io/react_article/)

2022-10-11 10:52 UTC, Vladosik1337 approved these changes
Nice 🔥

2022-10-11 10:52 UTC, Vladosik1337 commented on src/App.jsx
> +      />
![image](https://user-images.githubusercontent.com/36279782/195071605-e4cdef08-d3d1-47ef-a603-1b77218486d8.png)

2022-10-12 07:41 UTC, naziamoff requested changes
good point above

2022-10-12 12:54 UTC, naziamoff approved these changes
🔥

2025-09-02 10:19 UTC, closed without merging