added solution
mate-academy/react_article pull request #1256
Opened 2022-11-15 21:15 UTC by kryvets-vadym

[DEMO LINK](https://kryvets-vadym.github.io/react_article/) and add it to the PR description.

2022-11-17 16:50 UTC, bohdan-stepanets requested changes

2022-11-17 16:50 UTC, bohdan-stepanets commented on src/components/Article.jsx
> +      <div className="container">
As I understand this task, you need to write only article, but not all section

2022-11-17 17:29 UTC, bohdan-stepanets approved these changes
Good job! 🔥

2022-11-18 16:33 UTC, mykola-koval approved these changes

2024-01-15 14:09 UTC, closed without merging