added the Article component
mate-academy/react_article pull request #297
Opened 2021-03-15 14:38 UTC by SofiiaAsieieva

[DEMO LINK](https://SofiiaAsieieva.github.io/react_article/)

2021-03-15 16:06 UTC, AnnaHarshyna approved these changes
well done!

2021-03-16 09:46 UTC, Vladimir-Beliy requested changes

2021-03-16 09:46 UTC, Vladimir-Beliy commented on src/App.js
> +    <h1>React Article</h1>
только один тег h1

2021-03-16 12:48 UTC, Vladimir-Beliy approved these changes

2026-02-02 20:01 UTC, closed without merging