article
mate-academy/react_article pull request #443
Opened 2021-07-16 13:17 UTC by gponomarenko

[DEMO LINK](https://gponomarenko.github.io/react_article/)

2021-07-16 13:31 UTC, Vivdyuk requested changes
Not bad, але є лови трохи коментів на вентилятор)

2021-07-16 13:31 UTC, Vivdyuk commented on src/App.js
> +    <Article title={article.title} date={article.date} text={article.text} />
Враховуючи, що в тебе 3 параметри з присвоєнням, то краще переносити все на окремий рядок
```suggestion
    <Article 
      title={article.title} 
      date={article.date} 
      text={article.text} 
    />
```

2021-07-16 13:31 UTC, Vivdyuk commented on src/components/Article.jsx
> +  const {title, date, text} = props;
Можна деструктуризацію проводити в самому прийомі аргументу для **Article**

2021-07-16 13:31 UTC, Vivdyuk commented on src/components/Article.jsx
> +  title: 'some title',
Так як в тебе **title** має припис **isRequired**, то дефолтне значення для нього не потрібне

2021-07-16 13:32 UTC, gponomarenko commented on src/App.js
> +    <Article title={article.title} date={article.date} text={article.text} />
Приймається! Дякую!

2021-07-16 13:33 UTC, gponomarenko commented on src/components/Article.jsx
> +  title: 'some title',
+

2021-07-16 13:34 UTC, gponomarenko commented on src/components/Article.jsx
> +  title: 'some title',
тоді приберу isRequired

2021-07-16 13:34 UTC, gponomarenko commented on src/components/Article.jsx
> +  const {title, date, text} = props;
`+`

2021-07-16 13:38 UTC, gponomarenko commented
Підправив!

2021-07-16 13:39 UTC, Vivdyuk approved these changes
Пушка

2021-07-16 13:57 UTC, gponomarenko commented
> Пушка

МегаПодяка!

2021-07-19 06:45 UTC, ArtemTopolskyi approved these changes

2021-07-19 06:45 UTC, ArtemTopolskyi commented on src/components/Article.jsx
> +  text: 'some text',
думаю здесь нет смысла использовать defaultProps

2021-07-19 07:39 UTC, gponomarenko commented on src/components/Article.jsx
> +  text: 'some text',
дякую, врахую!

2023-11-06 19:05 UTC, closed without merging