solutions
mate-academy/react_article pull request #530
Opened 2021-10-07 16:15 UTC by caelum29

[DEMO LINK](https://caelum29.github.io/react_article/)

2021-10-08 08:29 UTC, vlad-shulzhenko approved these changes
Хорошая работа!)

2021-10-08 15:01 UTC, aliceblunt8 requested changes

2021-10-08 15:01 UTC, aliceblunt8 commented on src/App.js
> +  <Article title={article.title} text={article.text} date={article.date} />
```suggestion
  <Article
    title={article.title}
    text={article.text}
    date={article.date}
  />
```

2021-10-08 15:01 UTC, aliceblunt8 commented on src/components/Article.jsx
> +};
make all props required

2021-10-11 06:53 UTC, Anna-Tkachenko approved these changes
Pay attention to @aliceblunt8 comment. You didn't fix it

2025-10-31 11:25 UTC, closed without merging