solution
mate-academy/react_article pull request #845
Opened 2022-05-25 19:23 UTC by lytvyshko

- [DEMO LINK](https://lytvyshko.github.io/react_article/)

2022-05-25 20:37 UTC, EnjSadman approved these changes

2022-05-26 11:39 UTC, Denchepornyuk requested changes

2022-05-26 11:39 UTC, Denchepornyuk commented on src/components/Article.js
> +export const Article = ({ title, date, text }) => (
add propTypes for the component

2022-05-28 20:48 UTC, Anna-Tkachenko approved these changes
⭐️

2024-04-01 10:07 UTC, closed without merging