Solution
mate-academy/react_article pull request #875
Opened 2022-05-31 14:16 UTC by PRO-GRAM-MER

[DEMO LINK](https://pro-gram-mer.github.io/react_article/)

2022-06-03 12:25 UTC, rHashTag approved these changes
Looks good to me! Well done.

Just a note, you only need to push the files from the SRC folder.

2022-06-06 07:27 UTC, meforoma requested changes

2022-06-06 07:27 UTC, meforoma commented on src/components/Article.js
> +Article.prototype = {
`.prototype`? or `.propTypes`? 🙂

2022-06-06 08:32 UTC, meforoma approved these changes

2026-03-29 20:35 UTC, closed without merging